deploy updates

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,7 @@ on:
   pull_request:
     branches: [master]
 jobs:
-  build:
+  build_test:
     name: Build and Test
     runs-on: windows-latest
 
@@ -31,10 +31,43 @@ jobs:
         run: ng lint
 
       - name: Run unit tests
-        run: ng test --watch=false --browsers=ChromeHeadless
+        run: |
+          ng test --watch=false --browsers=ChromeHeadless
+          if ($?) {
+            echo "✅ Tests Passed!"
+          } else {
+            echo "❌ Tests Failed!"
+            exit 1
+          }
+        shell: pwsh
 
       - name: Build Angular project
         run: ng build --configuration production
 
-      - name: List build files
-        run: dir dist
+  Deploy-Preview:
+    runs-on: ubuntu-latest
+    needs: build_test
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install Vercel CLI
+        run: npm install --global vercel@latest
+      - name: Pull Vercel Environment Information
+        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Build Project Artifacts
+        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Deploy Project Artifacts to Vercel
+        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
+
+  Deploy-Production:
+    runs-on: ubuntu-latest
+    needs: Deploy-Preview
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install Vercel CLI
+        run: npm install --global vercel@latest
+      - name: Pull Vercel Environment Information
+        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Build Project Artifacts
+        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Deploy Project Artifacts to Vercel
+        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
